version: "3.9"

services:
  planus_back:
    build:
      context: ./planus_back
    image: planus_back_green
    container_name: planus_back-green
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-container:3306/planus"
      SPRING_DATASOURCE_USERNAME: "ssafy"
      SPRING_DATASOURCE_PASSWORD: "ssafyA505!"
      TZ: "Asia/Seoul"

  planus_front:
    build:
      context: ./planus_front
    image: planus_front_green
    container_name: planus_front-green
    ports:
      - "8091:80"
    environment:
      TZ: "Asia/Seoul"

  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/home/ubuntu/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "planusA505!"
      MYSQL_DATABASE: "planus"
      MYSQL_USER: "ssafy"
      MYSQL_PASSWORD: "ssafyA505!"
      TZ: "Asia/Seoul"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"

  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "/home/ubuntu/redis:/data"
    environment:
      TZ: "Asia/Seoul"
      - REDIS_PASSWORD="Tkvlvmffosjtm"
